[prune]
  go-tests = true
  unused-packages = true

# Stupid fsnotify and dep stuff https://github.com/golang/dep/issues/777
[[override]]
  name = "gopkg.in/fsnotify.v1"
  source = "gopkg.in/fsnotify/fsnotify.v1"


[[constraint]]
  branch = "master"
  name = "github.com/kr/beanstalk"

[[constraint]]
  branch = "master"
  name = "github.com/syndtr/goleveldb"
